services:
  database:
    image: mongo:latest
    container_name: anti-social-grupo-2-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  cliente:
    image: mongo-express
    container_name: anti-social-grupo-2-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
      ME_CONFIG_BASICAUTH: false

  api:
    build: ./
    container_name: anti-social-grupo-2-api
    ports:
      - 4001:3005
    environment:
      PORT: 3005
      MONGO_URL: mongodb://root:example@database:27017/libros?authSource=admin
    depends_on:
      - database
